# Nome do Workflow
name: Deploy to GitHub Pages

# Gatilho: Executar quando houver um push na branch "main"
on:
  push:
    branches:
      - main
  # Permite que você rode este workflow manualmente pela aba Actions
  workflow_dispatch:

# Permissões necessárias para o deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Tarefas a serem executadas
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configura o ambiente do GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3. Cria o "artefato" (a pasta do site) para o deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Usa a raiz do repositório como a fonte do site
          path: '.'

      # 4. Faz o deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
